name: deployment of github
on:
  push:
    branches:
      - "master"
jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: deployment in serv
        uses: SISTEMASMIT/sistemasmyc@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}