name: deployment of github
on:
  push:
    branches:
      - "master"
jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: deployment in serv
        run: |
          ssh webapi@149.56.23.5 -p 23522
      - name: password process
        run: |
          D1CrYx=p4g.apw$$69
