name: deployment of github
on:
  push:
    branches:
      - "master"
jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: connect to serv
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo ls
            sudo cd ..
            sudo cd webapi
            sudo cd sistemasmyc
            sudo git pull master master 

             
